---
# Private Registry Configuration

- name: Run private registry image
  docker:
    name: private_registry
    image: registry:2
    state: reloaded
    restart_policy: always
    detach: True
    ports:
    - "5000:5000"
